# Basic Python

## 1. Split this string

In [63]:
s = "Hi there Sam!"

In [64]:
for i in s.split(" "):
  print(i)

Hi
there
Sam!


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [65]:
planet = "Earth"
diameter = 12742

In [66]:
print("The diameter of Earth is %d kilometers"%(12742))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [67]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [68]:
d.get('k1')[3].get('tricky')[3].get('target')[3]


'hello'

# Numpy

In [69]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [70]:
np.zeros((10),dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [71]:
np.array([5]*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [72]:
[k for k in range(20,36) if k%2==0]
  

[20, 22, 24, 26, 28, 30, 32, 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [73]:
np.array([i for i in range(9)]).reshape(((3,3)))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.array((list(a)+list(b))))


[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [75]:
import pandas as pd

In [76]:
pd.DataFrame({"NAME":["kumar","John","Peter"],"AGE":[34,54,31]},index=[1,2,3])

NAME  AGE
1  kumar   34
2   John   54
3  Peter   31

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [125]:
date1 = [i for i in range(1,32)]
date2 = [k for k in range(1,11)]

month1 = ["Jan"]*31
month2 = ["Feb"]*10


In [126]:
pd.Series(date1+date2, index =[month1+month2] )

Jan     1
Jan     2
Jan     3
Jan     4
Jan     5
Jan     6
Jan     7
Jan     8
Jan     9
Jan    10
Jan    11
Jan    12
Jan    13
Jan    14
Jan    15
Jan    16
Jan    17
Jan    18
Jan    19
Jan    20
Jan    21
Jan    22
Jan    23
Jan    24
Jan    25
Jan    26
Jan    27
Jan    28
Jan    29
Jan    30
Jan    31
Feb     1
Feb     2
Feb     3
Feb     4
Feb     5
Feb     6
Feb     7
Feb     8
Feb     9
Feb    10
dtype: int64

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [127]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [129]:
pd.DataFrame(lists, columns=['S.No:','Name','Age'])

S.No: Name  Age
0      1  aaa   22
1      2  bbb   25
2      3  ccc   24